name: Test Branch

on: push

jobs:
    run-tests:
        name: Run Tests
        strategy:
            matrix:
                version: [18, 16, 14]
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Set up Node
            uses: actions/setup-node@v3
            with:
                node-version: ${{ matrix.version }}
          - name: Install dependencies
            run: npm ci
          - name: Run Tests
            run: ./node_modules/.bin/jest --coverage
    validate-types:
        name: Validate Types
        strategy:
            matrix:
                version: [18, 16, 14]
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Set up Node
            uses: actions/setup-node@v3
            with:
                node-version: ${{ matrix.version }}
          - name: Install dependencies
            run: npm ci
          - name: Run TypeScript
            run: ./node_modules/.bin/tsc
